version: '2'
services:
  nginx:
    image: nginx
    ports:
        - "80:80"
    build: ./nginx
    links:
        - django_server
    depends_on: 
        - django_server
  django_server:
    build: ./docker_server
    expose: 
        - "8000"