version: '2'
services:
  nginx:
    image: nginx
    ports:
        - "80:80"
    build: ./nginx
    links:
        - django_server:web
    depends_on: 
        - django_server
  django_server:
    build: ./django_server
    expose: 
        - "8000"