version: '2'
services:
  nginx:
    ports:
        - "80:80"
    build: ./nginx
    links:
        - django_server:web
    volumes_from:
        - angular2
  angular2:
    build: ./angular2
    entrypoint: "true"
    volumes:
        - /usr/share/nginx/angular2
  django_server:
    build: ./django_server
    expose: 
        - "8000"
    links:
        - redis:redis
  redis:
    image: redis
    #command: "./docker-entrypoint.sh"